
// Macro generated by assembly definition 
// com.unity.render-pipelines.universal >= 17.3.0
#if UNITY_BREAKING_URP_VERSION_PRESENT
using System;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.RenderGraphModule;
using UnityEngine.Rendering.Universal;

namespace URPMigration
{
    public class UnityURPBackwardsCompatibilityRenderFeature : ScriptableRendererFeature
    {
        private static RTHandle GlobalRenderTexture;
        
        public static string TextureName { get; set; } = "_CompatibilityRenderTextureHolder";

        // Custom pass data
        private class PassData
        {
            public TextureHandle Source;
            public TextureHandle Destination;
        }

        private class ClearPassData
        {
            public Color Color;
            public TextureHandle Destination;
        }
        
        public static void TidyAndImportTexture(RenderGraph renderGraph, UniversalResourceData resourceData, ref RTHandle globalRenderTexture, out TextureHandle outTex)
        {
            var descriptor = resourceData.activeColorTexture.GetDescriptor(renderGraph);
            
            RenderTextureDescriptor rtd =
                new RenderTextureDescriptor(descriptor.width, descriptor.height, descriptor.colorFormat, 0);
            rtd.msaaSamples = 1;
            RenderingUtils.ReAllocateHandleIfNeeded(ref globalRenderTexture, rtd, name: TextureName);
            outTex = renderGraph.ImportTexture(globalRenderTexture);
        }
        
        public class CameraColorTextureToTexturePass : ScriptableRenderPass
        {
            public CameraColorTextureToTexturePass()
            {
                renderPassEvent = (RenderPassEvent)999;
                ConfigureInput(ScriptableRenderPassInput.Color);
            }
            
            public override void RecordRenderGraph(RenderGraph renderGraph, ContextContainer frameData)
            {
                var resourceData = frameData.Get<UniversalResourceData>();
                
                //renderGraph.AddCopyPass(resourceData.activeColorTexture, destinationTextureHandle, passName: "Frame to texture copy");
                using (var builder = renderGraph.AddRasterRenderPass<PassData>("Camera Color Texture to texture", out var passData))
                {
                    TidyAndImportTexture(renderGraph, resourceData, ref GlobalRenderTexture,
                        out TextureHandle destinationTextureHandle);
                    passData.Source = resourceData.activeColorTexture;
                    passData.Destination = destinationTextureHandle;
                    builder.UseTexture(passData.Source, AccessFlags.Read);
                    //builder.UseTexture(passData.Destination, AccessFlags.Write);
                    builder.SetRenderAttachment(passData.Destination, 0);
                    builder.SetRenderFunc(static (PassData passData, RasterGraphContext context) =>
                    {
                        Blitter.BlitTexture(context.cmd, passData.Source, new Vector4(1,1,0,0), 0, false);
                    });
                }
            }
        }
        
        public class TextureToCameraColorTexturePass : ScriptableRenderPass
        {
            private Camera _camera;

            public TextureToCameraColorTexturePass()
            {
                renderPassEvent = RenderPassEvent.BeforeRenderingPrePasses;
                ConfigureInput(ScriptableRenderPassInput.Color);
            }
            public void Setup(RenderingData renderingData)
            {
                _camera = renderingData.cameraData.camera;
            }
            
            public override void RecordRenderGraph(RenderGraph renderGraph, ContextContainer frameData)
            {
                var resourceData = frameData.Get<UniversalResourceData>();
                
                //renderGraph.AddCopyPass(sourceTextureHandle, resourceData.activeColorTexture, passName: "Texture to frame pass");
                using (var builder = renderGraph.AddRasterRenderPass<PassData>("Texture to camera color texture", out var passData))
                {
                    TidyAndImportTexture(renderGraph, resourceData, ref GlobalRenderTexture,
                        out TextureHandle sourceTextureHandle);
                    passData.Source = sourceTextureHandle;
                    passData.Destination = resourceData.activeColorTexture;
                    builder.UseTexture(passData.Source, AccessFlags.Read);
                    //builder.UseTexture(passData.Destination, AccessFlags.Write);
                    builder.SetRenderAttachment(passData.Destination, 0);
                    builder.SetRenderFunc(static (PassData passData, RasterGraphContext context) =>
                    {
                        Blitter.BlitTexture(context.cmd, passData.Source, new Vector4(1,1,0,0), 0, false);
                    });
                }

                if (_camera != null && _camera.clearFlags == CameraClearFlags.SolidColor)
                {
                    using (var builder =
                           renderGraph.AddRasterRenderPass<ClearPassData>("Clear with color", out var passData))
                    {
                        passData.Color = _camera.backgroundColor; 
                        passData.Destination = resourceData.activeColorTexture;
                        builder.SetRenderAttachment(passData.Destination, 0);
                        builder.SetRenderFunc(static (ClearPassData passData, RasterGraphContext context) =>
                        {
                            context.cmd.ClearRenderTarget(false, true, passData.Color);
                        });
                    }
                }
            }
        }
        
        #region runtime 
        private CameraColorTextureToTexturePass _cameraColorTextureToTexturePass;
        private TextureToCameraColorTexturePass _textureToCameraColorTexturePass;
        #endregion
        
        public override void Create()
        {
            GlobalRenderTexture = null; // Allocate on first pass
            _textureToCameraColorTexturePass = new TextureToCameraColorTexturePass();
            _cameraColorTextureToTexturePass = new CameraColorTextureToTexturePass();
        }

        public override void AddRenderPasses(ScriptableRenderer renderer, ref RenderingData renderingData)
        {
            if (renderingData.cameraData.cameraType == CameraType.Game)
            {
                _textureToCameraColorTexturePass.Setup(renderingData);
                renderer.EnqueuePass(_textureToCameraColorTexturePass);
                renderer.EnqueuePass(_cameraColorTextureToTexturePass);
            }
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            GlobalRenderTexture?.Release();
        }
    }
}
#endif