
// Macro generated by assembly definition 
// com.unity.render-pipelines.universal >= 17.3.0
#if UNITY_BREAKING_URP_VERSION_PRESENT
using System;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.RenderGraphModule;
using UnityEngine.Rendering.Universal;

namespace URPMigration
{
    public class UnityURPBackwardsCompatibilityRenderFeature : ScriptableRendererFeature
    {
        private static RTHandle _globalRenderTexture;
        
        public static string FrameTextureName { get; set; } = "_FrameTextureHolder";

        // Custom pass data
        private class PassData
        {
            public TextureHandle Source;
            public TextureHandle Destination;
        }

        private class ClearPassData
        {
            public Color Color;
            public TextureHandle Destination;
        }
        
        public static void TidyAndImportTexture(RenderGraph renderGraph, UniversalResourceData resourceData, ref RTHandle globalRenderTexture, out TextureHandle outTex)
        {
            var descriptor = resourceData.activeColorTexture.GetDescriptor(renderGraph);
            
            RenderTextureDescriptor rtd =
                new RenderTextureDescriptor(descriptor.width, descriptor.height, descriptor.colorFormat, 0);
            rtd.msaaSamples = 1;
            RenderingUtils.ReAllocateHandleIfNeeded(ref globalRenderTexture, rtd, name: FrameTextureName);
            

            outTex = renderGraph.ImportTexture(globalRenderTexture);
        }

        public class ClearWithColorPass : ScriptableRenderPass
        {
            private readonly Color _cameraClearColor;
            public ClearWithColorPass(Camera camera)
            {
                if (camera == null)
                {
                    throw new ArgumentNullException("Cannot clear with null camera.");
                }

                if (camera.clearFlags != CameraClearFlags.SolidColor)
                {
                    throw new NotImplementedException("This pass should only be used for solid color clear.");
                }

                ConfigureInput(ScriptableRenderPassInput.Color);
                _cameraClearColor = camera.backgroundColor;
            }
            
            public override void RecordRenderGraph(RenderGraph renderGraph, ContextContainer frameData)
            {
                using (var builder =
                       renderGraph.AddRasterRenderPass<ClearPassData>("Clear with color", out var passData))
                {
                    var resourceData = frameData.Get<UniversalResourceData>();
                    passData.Color = _cameraClearColor; 
                    passData.Destination = resourceData.activeColorTexture;
                    builder.SetRenderAttachment(passData.Destination, 0);
                    builder.SetRenderFunc(static (ClearPassData passData, RasterGraphContext context) =>
                    {
                        context.cmd.ClearRenderTarget(false, true, passData.Color);
                    });
                }
            }
        }
        
        public class FrameBufferToTexturePass : ScriptableRenderPass
        {
            public override void RecordRenderGraph(RenderGraph renderGraph, ContextContainer frameData)
            {
                var resourceData = frameData.Get<UniversalResourceData>();
                
                //renderGraph.AddCopyPass(resourceData.activeColorTexture, destinationTextureHandle, passName: "Frame to texture copy");
                using (var builder = renderGraph.AddRasterRenderPass<PassData>("Texture to frame buffer", out var passData))
                {
                    TidyAndImportTexture(renderGraph, resourceData, ref _globalRenderTexture,
                        out TextureHandle destinationTextureHandle);
                    passData.Source = resourceData.activeColorTexture;
                    passData.Destination = destinationTextureHandle;
                    builder.UseTexture(passData.Source, AccessFlags.Read);
                    //builder.UseTexture(passData.Destination, AccessFlags.Write);
                    builder.SetRenderAttachment(passData.Destination, 0);
                    builder.SetRenderFunc(static (PassData passData, RasterGraphContext context) =>
                    {
                        Blitter.BlitTexture(context.cmd, passData.Source, new Vector4(1,1,0,0), 0, false);
                    });
                }
            }
        }
        
        public class TextureToFrameBufferPass : ScriptableRenderPass
        {
            public override void RecordRenderGraph(RenderGraph renderGraph, ContextContainer frameData)
            {
                var resourceData = frameData.Get<UniversalResourceData>();
                
                //renderGraph.AddCopyPass(sourceTextureHandle, resourceData.activeColorTexture, passName: "Texture to frame pass");
                using (var builder = renderGraph.AddRasterRenderPass<PassData>("Texture to frame buffer", out var passData))
                {
                    TidyAndImportTexture(renderGraph, resourceData, ref _globalRenderTexture,
                        out TextureHandle sourceTextureHandle);
                    passData.Source = sourceTextureHandle;
                    passData.Destination = resourceData.activeColorTexture;
                    builder.UseTexture(passData.Source, AccessFlags.Read);
                    //builder.UseTexture(passData.Destination, AccessFlags.Write);
                    builder.SetRenderAttachment(passData.Destination, 0);
                    builder.SetRenderFunc(static (PassData passData, RasterGraphContext context) =>
                    {
                        Blitter.BlitTexture(context.cmd, passData.Source, new Vector4(1,1,0,0), 0, false);
                    });
                }
            }
        }
        
        #region runtime 
        private FrameBufferToTexturePass _frameBufferToTexturePass;
        private TextureToFrameBufferPass _textureToFrameBufferPass;
        #endregion
        
        public override void Create()
        {
            _globalRenderTexture = null; // Allocate on first pass
            _textureToFrameBufferPass = new TextureToFrameBufferPass();
            _textureToFrameBufferPass.renderPassEvent = RenderPassEvent.BeforeRenderingPrePasses;
            _textureToFrameBufferPass.ConfigureInput(ScriptableRenderPassInput.Color);
            _frameBufferToTexturePass = new FrameBufferToTexturePass();
            _frameBufferToTexturePass.renderPassEvent = (RenderPassEvent)999;
            _frameBufferToTexturePass.ConfigureInput(ScriptableRenderPassInput.Color);
        }

        public override void AddRenderPasses(ScriptableRenderer renderer, ref RenderingData renderingData)
        {
            if (renderingData.cameraData.cameraType == CameraType.Game)
            {
                renderer.EnqueuePass(_textureToFrameBufferPass);
                if (renderingData.cameraData.camera.clearFlags.HasFlag(CameraClearFlags.Color))
                {
                    // URP / SRP seems not to do clearing for the color
                    // .. or more likely its timed so that it gets overriden by the frame buffer write
                    
                    // Hence clear manually
                    //Debug.Log("Setting up clearing background for " + renderingData.cameraData.camera.name);
                    var pass = new ClearWithColorPass(renderingData.cameraData.camera);
                    pass.renderPassEvent = RenderPassEvent.AfterRenderingPrePasses;
                    renderer.EnqueuePass(pass);
                }
                renderer.EnqueuePass(_frameBufferToTexturePass);
            }
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _globalRenderTexture?.Release();
        }
    }
}
#endif